package:
    name: runjb
    version: 0.1

build:
  number: 0
  script: python copy_file.py

source:
  path: ../

requirements:
  build:
    - python ==3.7.*

test:
  commands:
    - if exist %PREFIX%\bin\runjb.ps1 (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\bin\runmyst.ps1 (exit 0) else (exit 1)  # [win]
    - test -f ${PREFIX}/bin/runmyst.sh  # [unix]
    - test -f ${PREFIX}/bin/runjb.sh  # [unix]

about:
  summary: powershell and bash tools
  license_file: LICENSE

