package:
    name: jbwin
    version: 0.1

build:
  number: 0

source:
  path: ../

requirements:
  build:
    - python ==3.7.*


test:
  commands:
    - testbin.sh # [not win]
    - testbin.bat # [win]


about:
  summary: powershell and bash tools
  license_file: LICENSE

